FROM node:22.15-slim
# FROM node:20
RUN apt-get update && apt-get install -y openssl
WORKDIR /app
COPY package*.json ./
COPY src/prisma ./prisma
RUN npm install --omit=dev
ENV DATABASE_URL=$PROD_DATABASE_URL
RUN npx prisma generate && npx prisma migrate deploy
COPY . .
RUN npm run build
EXPOSE 5000
CMD [ "npm", "start" ]
