FROM node:22.15.0-alpine3.17
# FROM node:20
RUN apt-get update && apt-get install -y openssl
WORKDIR /app
COPY package*.json ./
COPY src/prisma ./prisma
RUN npm install 
ENV DATABASE_URL=$DATABASE_URL
RUN npx prisma generate && npx prisma migrate deploy
COPY . .
RUN npm run build
RUN npm install --omit=dev
EXPOSE 5000
CMD [ "npm", "start" ]
