# Build stage
FROM node:22.15-alpine3.21 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install --only=development

COPY src/prisma ./prisma

# RUN --mount=type=secret,id=my_db_url,target=/tmp/database_url \
#     DATABASE_URL=$(cat /tmp/database_url) npx prisma generate --schema=./prisma/schema.prisma

RUN npx prisma generate 

COPY . .
RUN npm run build

RUN npm prune --omit=dev

FROM node:22.15-alpine3.21
WORKDIR /app

COPY --from=builder /app/package*.json .
COPY --from=builder /app/package-lock.json .

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src/prisma ./prisma

EXPOSE 5000
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/app.mjs"]
# CMD [ "node", "dist/app.mjs" ]
