name: Keep Render Alive

on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          curl -f https://niap.onrender.com/ping || exit 0
          echo "✅ Render pinged at $(dat